### ISSUE TITLE
Upload a ML project

### ISSUE THREAD

**Issue by tauquirahmed** [tauquirahmed/Machine-Learning-Practice#3]

**Comment by Ripan-Roy** [comment]
assign me

**Comment by bembenk18** [comment]
🤔

**Comment by BassCoder2808** [comment]
Can you assign the issue to me as well @tauquirahmed

**Comment by then00bprogrammer** [comment]
Can you assign me as well @tauquirahmed

**Comment by gsm005** [comment]
Hey I can provide a mapping feature. That will map the current location of a person in the map.

**Comment by gsm005** [comment]
Can you assign me as you can merge this mapping feature with face detection to map the location of the person when his face is detected @tauquirahmed.

**Comment by gsm005** [comment]
I have made a PR. Please check it. Hope you will definitely merge it!

**Comment by tauquirahmed** [comment]
> Can you assign the issue to me as well @tauquirahmed

Yes sure

**Comment by tauquirahmed** [comment]
> Can you assign me as you can merge this mapping feature with face detection to map the location of the person when his face is detected @tauquirahmed.

Sounds interesting, will surely merge this file.

**Comment by navya-Singla-1-3-0-9** [comment]
Please assign this issue to me.
